apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-hlm
  namespace: nginx
spec:
  interval: 5m
  chart:
    spec:
      chart: nginx
      version: 1.2.3   # pick the version available in Artifactory
      sourceRef:
        kind: HelmRepository
        name: artifactory-repo
        namespace: flux-system
  values:
    replicaCount: 2
    service:
      type: ClusterIP
      port: 80
